// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package dto

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// ActionTypeKvGet is a ActionType of type Kv_get.
	ActionTypeKvGet ActionType = iota
	// ActionTypeKvSet is a ActionType of type Kv_set.
	ActionTypeKvSet
	// ActionTypeKvDelete is a ActionType of type Kv_delete.
	ActionTypeKvDelete
	// ActionTypeKvList is a ActionType of type Kv_list.
	ActionTypeKvList
)

var ErrInvalidActionType = fmt.Errorf("not a valid ActionType, try [%s]", strings.Join(_ActionTypeNames, ", "))

const _ActionTypeName = "kv_getkv_setkv_deletekv_list"

var _ActionTypeNames = []string{
	_ActionTypeName[0:6],
	_ActionTypeName[6:12],
	_ActionTypeName[12:21],
	_ActionTypeName[21:28],
}

// ActionTypeNames returns a list of possible string values of ActionType.
func ActionTypeNames() []string {
	tmp := make([]string, len(_ActionTypeNames))
	copy(tmp, _ActionTypeNames)
	return tmp
}

var _ActionTypeMap = map[ActionType]string{
	ActionTypeKvGet:    _ActionTypeName[0:6],
	ActionTypeKvSet:    _ActionTypeName[6:12],
	ActionTypeKvDelete: _ActionTypeName[12:21],
	ActionTypeKvList:   _ActionTypeName[21:28],
}

// String implements the Stringer interface.
func (x ActionType) String() string {
	if str, ok := _ActionTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ActionType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActionType) IsValid() bool {
	_, ok := _ActionTypeMap[x]
	return ok
}

var _ActionTypeValue = map[string]ActionType{
	_ActionTypeName[0:6]:   ActionTypeKvGet,
	_ActionTypeName[6:12]:  ActionTypeKvSet,
	_ActionTypeName[12:21]: ActionTypeKvDelete,
	_ActionTypeName[21:28]: ActionTypeKvList,
}

// ParseActionType attempts to convert a string to a ActionType.
func ParseActionType(name string) (ActionType, error) {
	if x, ok := _ActionTypeValue[name]; ok {
		return x, nil
	}
	return ActionType(0), fmt.Errorf("%s is %w", name, ErrInvalidActionType)
}

// MarshalText implements the text marshaller method.
func (x ActionType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ActionType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseActionType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ActionType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errActionTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ActionType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ActionType(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = ActionType(v)
	case string:
		*x, err = ParseActionType(v)
	case []byte:
		*x, err = ParseActionType(string(v))
	case ActionType:
		*x = v
	case int:
		*x = ActionType(v)
	case *ActionType:
		if v == nil {
			return errActionTypeNilPtr
		}
		*x = *v
	case uint:
		*x = ActionType(v)
	case uint64:
		*x = ActionType(v)
	case *int:
		if v == nil {
			return errActionTypeNilPtr
		}
		*x = ActionType(*v)
	case *int64:
		if v == nil {
			return errActionTypeNilPtr
		}
		*x = ActionType(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = ActionType(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errActionTypeNilPtr
		}
		*x = ActionType(*v)
	case *uint:
		if v == nil {
			return errActionTypeNilPtr
		}
		*x = ActionType(*v)
	case *uint64:
		if v == nil {
			return errActionTypeNilPtr
		}
		*x = ActionType(*v)
	case *string:
		if v == nil {
			return errActionTypeNilPtr
		}
		*x, err = ParseActionType(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x ActionType) Value() (driver.Value, error) {
	return x.String(), nil
}
