package managerrepo

import (
	"time"

	"github.com/google/uuid"
	"github.com/rs/zerolog"
)

type Application struct {
	ID             uuid.UUID         `gorm:"primaryKey;autoIncrement" json:"id"`
	CreatedAt      time.Time         `gorm:"not null;autoCreateTime"  json:"createdAt"`
	UpdatedAt      time.Time         `gorm:"not null;autoUpdateTime"  json:"updatedAt"`
	LastAccessedAt time.Time         `gorm:"not null"                 json:"lastAccessedAt"`
	Status         ApplicationStatus `gorm:"not null"                 json:"status"`

	Title         string  `gorm:"not null"                json:"title"`
	Description   string  `gorm:"not null"                json:"description"`
	Slug          string  `gorm:"uniqueIndex;not null"    json:"slug"`
	UserPrompt    string  `gorm:"not null"                json:"userPrompt"`
	BackendPrompt *string `json:"backendPrompt,omitempty"`
}

// ApplicationStatus
// ENUM(CREATING, ACTIVE, ARCHIVED)
//
//go:generate go tool go-enum --sql --marshal --names -f models.go
type ApplicationStatus int //nolint: recvcheck // autogenerated

func (r *Application) MarshalZerologObject(e *zerolog.Event) {
	e.Stringer("id", r.ID).
		Time("created_at", r.CreatedAt).
		Stringer("status", r.Status).
		Str("slug", r.Slug)
}

type ApplicationKV struct { // TODO добавить TTL
	ApplicationID uuid.UUID `gorm:"not null;primaryKey" json:"id"`
	Key           string    `gorm:"not null;primaryKey" json:"key"`

	CreatedAt time.Time `gorm:"not null;autoCreateTime" json:"createdAt"`
	UpdatedAt time.Time `gorm:"not null;autoUpdateTime" json:"updatedAt"`

	Value any `gorm:"not null;serializer:json" json:"value"`
}
