// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package managerrepo

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// ApplicationStatusCREATING is a ApplicationStatus of type CREATING.
	ApplicationStatusCREATING ApplicationStatus = iota
	// ApplicationStatusACTIVE is a ApplicationStatus of type ACTIVE.
	ApplicationStatusACTIVE
	// ApplicationStatusARCHIVED is a ApplicationStatus of type ARCHIVED.
	ApplicationStatusARCHIVED
)

var ErrInvalidApplicationStatus = fmt.Errorf("not a valid ApplicationStatus, try [%s]", strings.Join(_ApplicationStatusNames, ", "))

const _ApplicationStatusName = "CREATINGACTIVEARCHIVED"



var _ApplicationStatusNames = []string{
	_ApplicationStatusName[0:8],
	_ApplicationStatusName[8:14],
	_ApplicationStatusName[14:22],
}

// ApplicationStatusNames returns a list of possible string values of ApplicationStatus.
func ApplicationStatusNames() []string {
	tmp := make([]string, len(_ApplicationStatusNames))
	copy(tmp, _ApplicationStatusNames)
	return tmp
}

var _ApplicationStatusMap = map[ApplicationStatus]string{
	ApplicationStatusCREATING: _ApplicationStatusName[0:8],
	ApplicationStatusACTIVE:   _ApplicationStatusName[8:14],
	ApplicationStatusARCHIVED: _ApplicationStatusName[14:22],
}

// String implements the Stringer interface.
func (x ApplicationStatus) String() string {
	if str, ok := _ApplicationStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ApplicationStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ApplicationStatus) IsValid() bool {
	_, ok := _ApplicationStatusMap[x]
	return ok
}

var _ApplicationStatusValue = map[string]ApplicationStatus{
	_ApplicationStatusName[0:8]:   ApplicationStatusCREATING,
	_ApplicationStatusName[8:14]:  ApplicationStatusACTIVE,
	_ApplicationStatusName[14:22]: ApplicationStatusARCHIVED,
}

// ParseApplicationStatus attempts to convert a string to a ApplicationStatus.
func ParseApplicationStatus(name string) (ApplicationStatus, error) {
	if x, ok := _ApplicationStatusValue[name]; ok {
		return x, nil
	}
	return ApplicationStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidApplicationStatus)
}

// MarshalText implements the text marshaller method.
func (x ApplicationStatus) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ApplicationStatus) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseApplicationStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ApplicationStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errApplicationStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ApplicationStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ApplicationStatus(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = ApplicationStatus(v)
	case string:
		*x, err = ParseApplicationStatus(v)
	case []byte:
		*x, err = ParseApplicationStatus(string(v))
	case ApplicationStatus:
		*x = v
	case int:
		*x = ApplicationStatus(v)
	case *ApplicationStatus:
		if v == nil {
			return errApplicationStatusNilPtr
		}
		*x = *v
	case uint:
		*x = ApplicationStatus(v)
	case uint64:
		*x = ApplicationStatus(v)
	case *int:
		if v == nil {
			return errApplicationStatusNilPtr
		}
		*x = ApplicationStatus(*v)
	case *int64:
		if v == nil {
			return errApplicationStatusNilPtr
		}
		*x = ApplicationStatus(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = ApplicationStatus(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errApplicationStatusNilPtr
		}
		*x = ApplicationStatus(*v)
	case *uint:
		if v == nil {
			return errApplicationStatusNilPtr
		}
		*x = ApplicationStatus(*v)
	case *uint64:
		if v == nil {
			return errApplicationStatusNilPtr
		}
		*x = ApplicationStatus(*v)
	case *string:
		if v == nil {
			return errApplicationStatusNilPtr
		}
		*x, err = ParseApplicationStatus(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x ApplicationStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
